### ISSUE TITLE
Pseudo-code description of matching metrics

### ISSUE THREAD

**Issue by mm5330** [Columbia-DESDR/ethiopia#11]
for @J-Rebs 

three key metrics (I think these can replace the metrics that are currently in the tool; or, just comment them out):

example data:

Series A | Series B
-- | --
0 | 0.1
0 | 0
1 | 0.8
1 | 0
0 | 0.2

rows indexed by [i].

1) **True positive rate** (what we currently call "matching"):

for (each pair [x,y] of columns in the historical data) {

rate[x,y] = sum(x[i] > 0 & y[i] > 0) / sum(y[i] > 0) 

}

OUTPUT:

  | Series A | Series B
-- | -- | --
Series A | 1 | 0.5
Series B | 0.33 | 1

2) **True negative rate**:

for (each pair [x,y] of columns in the historical data) {

rate[x,y] = sum(x[i] == 0 & y[i] == 0) / sum(y[i] == 0) 

}

OUTPUT:

  | Series A | Series B
-- | -- | --
Series A | 1 | 0.33
Series B | 0.50 | 1

3) **Overall matching rate** (what Dan mentioned the other day):

for (each pair [x,y] of columns in the historical data) {

rate1[x,y] = sum(x[i] > 0 & y[i] > 0) / sum(y[i] > 0) 
rate2[x,y] = sum(x[i] == 0 & y[i] == 0) / sum(y[i] == 0) 

rate = mean(rate1,rate2)

}

OUTPUT:

  | Series A | Series B
-- | -- | --
Series A | 1.000 | 0.417
Series B | 0.417 | 1.000

**Comment by J-Rebs** [comment]
Hey @mm5330 , is the third statistic supposed to be an average of the first two?

**Comment by mm5330** [comment]
yes

**Comment by J-Rebs** [comment]
redeployed, so resolving for now
